version: '3'
  
services:
  app:
    build: .
    links:
      - postgres
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  
