version: '3'
  
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password 
    ports:
      - "5432:5432"
volumes:
  postgres-data: